development:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_dev6
  pool: 5
  host: localhost
  username: ofn
  password: food

test:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  host: localhost
  username: ofn
  password: food

#not used with heroku
production:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_prod
  pool: 5
  host : localhost
  username: ofn
  password: food

staging:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_prod
  pool: 5
  username: ofn
  password: f00d
